databases:
  - name: Sakebukuro_DB
    databaseName: database_db
    user: Sakebukuro
    region: singapore

services:
  - type: web
    name: Sakebukuro
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Sakebukuro_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false